version: '2'

networks:
  bddnetwork:
    driver: bridge

services:
 seleniumhub:
  image: selenium/hub:3.4.0-einsteinium
  ports:
    - "4444:4444"
  networks:
    - bddnetwork
 firefox:
  image: selenium/node-firefox:3.4.0-einsteinium
  links:
    - seleniumhub
  networks:
    - bddnetwork
 chrome:
  image: selenium/node-chrome:3.4.0-einsteinium
  links:
    - seleniumhub
  networks:
    - bddnetwork
